@startuml


database "MongoDB\n" {
    [Tagging Data] as D
}

package "Tagging Service" as TService {
    [Tagging API] as TAPI
    [Grouper] as G
    [TagUtils] as TU
    [MongoHelper] as MH
    [MiscSuggester] as MS
    [History] as H
    [AnswersLoader] as AL
    [ProgmisconHelper] as PGH

    TAPI -(0- TU

    G -0)- TU
    MS -0)- TU
    H -0)- TU
    TU -(0- AL
    TU -(0- MH
    TU -(0- PGH
}

package "Front End" {
    [Tagging UI] as tui
    [Tagging session] as ts

    tui -- ts
}

node "AssignmentService" as AS
node "Progmiscon" as PG

MH --(0-- D

AL --(0-- AS


ts -(0- TAPI

PGH -(0- PG


@enduml