version: '3'
services:

  web:
    build: ./frontend
    ports:
     - "8080:8080"
    volumes:
     - ./frontend:/app

  tagging-service:
    build: ./tagging-service
    ports:
    - "5000:5000"
    volumes:
    - ./tagging-service:/tagging_service